### ISSUE TITLE
Restart Server When Settings Change

### ISSUE THREAD

**Issue by maddes-b** [ralph-irving/plugin-CommunityFirmware#6]
When changing the settings of the Community Firmware Plugin, then please trigger a server restart, so that the change gets active.

**Comment by michaelherger** [comment]
Can you provide more context: which setting would require a restart in order to take effect?

**Comment by maddes-b** [comment]
That one:
![grafik](https://github.com/ralph-irving/plugin-CommunityFirmware/assets/565223/15d7d067-f1c9-4c69-a178-91d8e2787873)

Clients do not see the change until LMS restarted.

**Comment by michaelherger** [comment]
Ok, the problem here is that LMS would wait up to 24h before checking for firmware availability here. What we need to do is not to restart LMS (that's really Windows 95 style), but to tell the firmware update checker to get the updated information. Let me see whether I can find a fix for this.
